apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo-fe-deployment
  labels:
    app: kubernetes-demo-app
    type: fe
spec:
  selector:
    matchLabels:
      app: kubernetes-demo-app
      type: fe
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-demo-app
        type: fe
    spec:
      containers:
      - name: kubernetes-demo-frontend
        image: valtechchregistry.azurecr.io/kubernetes-demo-frontend
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: valtechchregistrysecret
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service-fe
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: kubernetes-demo-app
    type: fe