apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo-deployment
  labels:
    app: kubernetes-demo-app
    type: demo
spec:
  selector:
    matchLabels:
      app: kubernetes-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
      - name: kubernetes-demo
        image: valtechchregistry.azurecr.io/bkb-solr
        ports:
        - containerPort: 8983
      imagePullSecrets:
        - name: valtechchregistrysecret
