version: '3.8'
networks:
  services:
    name: kubernetes-demo

services:
  kubernetes-demo-proxy:
    image: valtechchregistry.azurecr.io/kubernetes-demo-proxy
    container_name: kubernetes-demo-proxy
    networks:
      - services
    environment:
      - BASE_FQDN=localhost
    ports:
     - 8080:8080

  kubernetes-demo-backend:
    image: valtechchregistry.azurecr.io/kubernetes-demo-backend
    container_name: kubernetes-demo-backend
    networks:
      - services
#    environment:
#      - SPRING_DEBUG=true
#    ports:
#     - 8080:8080
#    volumes: # Sample mount of current directory into docker at /var/kubernetes-demo-backend
#      - .:/var/kubernetes-demo-backend

  kubernetes-demo-frontend:
    image: valtechchregistry.azurecr.io/kubernetes-demo-frontend
    container_name: kubernetes-demo-frontend
    networks:
      - services
#    ports:
#      - 8080:8080
