version: '3.8'
networks:
  services:
    name: kubernetes-demo

services:
  kubernetes-demo-backend:
    image: valtech/kubernetes-demo-backend
    container_name: kubernetes-demo-backend
    networks:
      - services
#    environment:
#      - SPRING_DEBUG=true
    ports:
      - 8080:8080
    volumes: # Sample mount of current directory into docker at /var/kubernetes-demo-backend
      - .:/var/kubernetes-demo-backend
